[project]
name = 'protocol'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.ddd]
path = 'contracts/ddd.clar'
clarity_version = 2
epoch = 2.5

[contracts.dividend-traits]
path = 'contracts/dividend-traits.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
